% Demo Experiment
% 2021 by Clara Kuper
% based on rolfslab code

% System setup
% Clear the workspace and the screen
sca;
clear all;
clear mex;
clear functions;

% cursor goes home, command window scrolled up
home;

% Which experiment are we running?
expCode = 'Dot';
sprintf('Now running experiment %s',expCode);

% add the functions folder to searchpath and define storage paths
addpath('Functions/','Data/', 'Design/');

% Unify keys in case sb codes with a different system
KbName('UnifyKeyNames');

% Here we call some default settings for setting up Psychtoolbox
PsychDefaultSetup(2);

% Init random
rand('seed', sum(100 * clock));

%start a timer for the experiment
tic;

% define some settings for the experiment
global settings visual design;

settings.SYNCTEST = 0; % 1 runs synctest, 0 does not
settings.DEVICE = 'h'; % h for home or v for viewpixx

% do some general stuff
% get subject code
[datFileJ, datFileS, subCode, subPath] = getSubjectCode(expCode);

% prepare the screens                                   
setScreens;

% generate design for both parts
genDesign(subCode);

% prepare the stimuli
prepStim;

% Add experiment Info after OpenWindow so it's under the text generated by Screen
fprintf('\nManualInhibition\n');



% Display Instructions:
ListenChar(0);
DrawFormattedText(visual.window, 'Welcome to the experiment', 'center', 200, visual.textColor);
DrawFormattedText(visual.window, 'Press any key to start', 'center', 'center', visual.textColor);
Screen('Flip',visual.window);
KbPressWait;
% initialize the block names         


%% run the two experiments


for b = 1:design.nBlocks

    data.block(b) = runBlock(b, design.block(b));
    
end


DrawFormattedText(visual.window, 'Thanks for your participation', 'center', 'center', visual.textColor);

% save the data
save(sprintf('./Data/%s_data.mat',design.vpcode), 'data');
writetable(data2output(data), sprintf('./Data/%s_dat.csv',design.vpcode));
% save the design
save(sprintf('./Design/%s_design.mat',design.vpcode),'design'); 
writetable(data2output(design), sprintf('./Design/%s_dat.csv',design.vpcode));
    
% get timing and end
expEnd = toc;

fprintf('This experiment lasted %i minutes', round(expEnd/60,0));
sca;
Screen('CloseAll');
